blank_issues_enabled: false
contact_links:
  - name: Dicas
    url: https://github.com/backend-br/forum/discussions/new?category=dicas
    about: Compartilhe uma dica com a comunidade!

  - name: Discussão
    url: https://github.com/backend-br/forum/discussions/new?category=discussao
    about: Proponha discussões ou reflexões sobre assuntos relacionados ao mundo backend!

  - name: Mostre seu trabalho
    url: https://github.com/backend-br/forum/discussions/new?category=mostre-seu-trabalho
    about: Compartilhe o que tem criado e desenvolvido!

  - name: Perguntas e Respostas
    url: https://github.com/backend-br/forum/discussions/new?category=perguntas-e-respostas
    about: Faça perguntas para a comunidade!
